title: Zendesk Garden Jekyll Theme
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

baseurl: /jekyll-theme-zendesk-garden

search_enabled: true
auto_page_title: true

sidebar:
  - getting-started
  - label: Customization
    children:
      - sidebar
      - search
      - relative-nav
      - additional-config
  - development
